### ISSUE TITLE
why `ld` files were removed?

### ISSUE THREAD

**Issue by Maik93** [CommunityGD32Cores/gd32-pio-spl-package#11]
Hi,
I'd like to understand why files like `GD32F130C8T_DEFAULT.ld` have been removed from `platformio/ldscripts`.
They exists in previous commits (e.g. 4ddfb48, up to commit 9e9c16ba8574e88894f7e13ac4c1e4758cce1a15) and are, as far as I know, necessary in PlatformIO projects to be specified in the `board_build.ldscript` entry.

**Comment by maxgerhardt** [comment]
They're not necessary. The builder script for SPL autogenerates them from the template file. See platform-gd32/builders/frameworks/spl.py. In fact, all .ld script but the template need to be deleted here.

**Comment by maxgerhardt** [comment]
Specifically,

https://github.com/CommunityGD32Cores/platform-gd32/blob/3014216a01af477a716b125286793fd6159713f4/builder/frameworks/spl.py#L77-L109
