### ISSUE TITLE
How to define platformio.ini for GD32F130C6T6

### ISSUE THREAD

**Issue by EFeru** [CommunityGD32Cores/gd32-pio-spl-package#6]
Hi @maxgerhardt , 
It is very nice that you are officially supporting the GD32 devices in 
https://github.com/platformio/platformio-core/issues/3927 and https://github.com/maxgerhardt/pio-gd32f130c6 is not needed anymore.

---
I tryied updating my [platformio.ini](https://github.com/EmanuelFeru/hoverboard-sideboard-hack-GD/blob/master/platformio.ini) but I am not sure how to do it correctly. I modified:
```c
[env]
platform_packages = maxgerhardt/framework-spl@2.10301.0
```
to
```c
[env]
platform = https://github.com/CommunityGD32Cores/platform-gd32.git
```
While the rest is kept the same, but it did not work. I get:
![image](https://user-images.githubusercontent.com/24780745/130104423-810b4caa-d643-4e4b-aea5-215982e93b8b.png)
 Any suggestions?

**Comment by maxgerhardt** [comment]
More settings changes are needed to use the new platform and its SPL package, please use at least

```
[env]
platform = https://github.com/CommunityGD32Cores/platform-gd32.git
platform_packages = 
    framework-spl-gd32@https://github.com/CommunityGD32Cores/gd32-pio-spl-package.git

[env:genericGD32F130C6]
board = genericGD32F130C6
framework = spl
```

as e.g. seen in https://github.com/CommunityGD32Cores/gd32-pio-projects/blob/main/gd32-spl-blinky/platformio.ini

**Comment by maxgerhardt** [comment]
Also

https://github.com/EmanuelFeru/hoverboard-sideboard-hack-GD/blob/1842991849854dd365733cbb69f1a1ec893cceee/platformio.ini#L33

isn't needed anymore as that is properly handled in the [build script](https://github.com/CommunityGD32Cores/platform-gd32/blob/e712045bdba54790ed2e07c47a421345340efb31/builder/frameworks/spl.py#L41-L45).

Let me just do a PR quickly.

**Comment by EFeru** [comment]
Solved. Thanks again!
